### ISSUE TITLE
Why 'cudnn.enabled = False'?

### ISSUE THREAD

**Issue by Eniac-Xie** [speedinghzl/Pytorch-Deeplab#1]
Hi, @speedinghzl 

Thanks for your sharing. I am a little curious why you set 'cudnn.enabled = False'? I set it to True and find it is faster and use less GPU memory. Will it have a bad influence on accuray? Thank you.

**Comment by speedinghzl** [comment]
Hi， @Eniac-Xie Thanks for your comment. I set 'cudnn.enabled = False' just for speed measurement. It doesn't affect the accuracy. I will correct the setting. Thank you.
