### ISSUE TITLE
Run on non-CUDA device

### ISSUE THREAD

**Issue by ddhgiang** [speedinghzl/Pytorch-Deeplab#11]
Hi, can I run the code on my laptop where I don't have a GPU that supports CUDA? Can you guide me how to make it work? Cheers.

**Comment by speedinghzl** [comment]
It's very time-consuming if you train deeplab on CPU. You can try to run testing on CPU by modify evaluate.py (.cuda(gpu0) -> .cpu() ).

**Comment by ddhgiang** [comment]
Thanks!! But then I couldn't load the pre-trained model where I got the error "No such file or directory: './deeplab_resnet.ckpt'". Can you show me where this file is?

**Comment by speedinghzl** [comment]
You can find the download link from the README.md. The init model and trained model are given.

**Comment by ddhgiang** [comment]
Hey sorry but I couldn't find the link to download deeplab_resnet.ckpt but I found one from your reference to the tensorflow-implemented model (https://drive.google.com/drive/folders/0B_rootXHuswsTF90M1NWQmFYelU).

However, when I tried to put it in the folder and ran the code, error still appeared:
UnpicklingError: invalid load key, '\x00'.

Is it in the README.md the file 'VOC12_scenes_20000.pth'?

**Comment by ddhgiang** [comment]
Also, could you explain why your replicated model achieve less accuracy, where you got 74% mIoU instead of 76.4% without CRF as the original paper did?
