### ISSUE TITLE
I have little question about gpu

### ISSUE THREAD

**Issue by EricKing19** [speedinghzl/Pytorch-Deeplab#12]
Thanks for your code, I have learned a lot from it.  But there are some question that  troubles me.
When I run code, I set args.gpu =1,  but I find the program always occupy memory in  gpu0. 

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      6721    C   python                                         399MiB |
|    1      6721    C   python                                        7215MiB |
+-----------------------------------------------------------------------------+

I don't know where is the problem, can you solve this?  Thanks a lot.

**Comment by speedinghzl** [comment]
I update the training code. Now this problem may be solved.
