### ISSUE TITLE
questions about data pre-processing

### ISSUE THREAD

**Issue by icoz69** [speedinghzl/Pytorch-Deeplab#13]
Hi,
thanks for the code sharing
have a few questions about the implementation.
1. why load a net pre trained on coco instead of using a pre trained net on Imagenet which is inbuilt in pytorch
2.why swap dimensions of 'R' and 'B'

**Comment by speedinghzl** [comment]
1. To achieve a better performance. Of course, you can use the Imagenet pre-trained model to initialize deeplab. 
2. I don't swap R and B channel in my code and I think it's unnecessary to swap the channels if the data processing is the same in training and testing.

**Comment by icoz69** [comment]
@speedinghzl 
```
#image = image[:, :, ::-1]  # change to BGR
image = image.transpose((2, 0, 1))
```
here is the related code . i dont know why

**Comment by speedinghzl** [comment]
But it is commented out. 

It appears as if opencv reads color images, by default, in BGR format. But in caffe classification task, the image means are saved in RGB format, the origin caffe swap the image channels. After that，this opreation has been retained.

**Comment by icoz69** [comment]
so when images are read by opencv its in BGR format and the network actually used RGB data ?
