### ISSUE TITLE
This is a fork of another repo: please cite original repo

### ISSUE THREAD

**Issue by isht7** [speedinghzl/Pytorch-Deeplab#14]
Hi, I am the author of [this repository](https://github.com/isht7/pytorch-deeplab-resnet). Your repository was brought to my notice recently. It seems that you have used a lot of my code and have not cited my repository. My repository has an MIT license. I would really appreciate if you cite my repository in your readme and mention that code in repo has been borrowed from my repo. 
Thanks.

**Comment by speedinghzl** [comment]
Thanks for your kind reminding. I add [acknowledgment](https://github.com/speedinghzl/Pytorch-Deeplab/commit/7fc1f0951c45a52fcb7ed1d8c72adaff37634f96) for your work in the readme. Thanks again.

**Comment by isht7** [comment]
Thanks much.
