### ISSUE TITLE
Some questions about image transposition

### ISSUE THREAD

**Issue by nihaomiao** [speedinghzl/Pytorch-Deeplab#15]
Hello, I am a master student in Beijing. I am reading your codes and I am confused about some questions.

In datasets.py, your 'Class VOCDataSet' reads image using 'cv2.imread', so your image should be 'BGR' channel order.  But then you use 'image = image.transpose((2, 0, 1))', so the image should be 'RBG' channel order. This really confused me a lot because I think that it should be 'RGB'.

Also, in datasets.py, when you show image, you use 'img = np.transpose(img, (1, 2, 0)), img = img[:, :, ::-1]'. And I also think that this way may generate an image that is not in 'RGB' channel order.

 It may just be my misunderstanding. But I am really looking forward to your reply. Thanks!!!

**Comment by speedinghzl** [comment]
Hi @HomerNee , The channel order of training images and test images should be the same, but needn't be "RGB" order. There is a mistake in your description. After image transposing, the "BGR" order of  image doesn't change to "RBG".

**Comment by nihaomiao** [comment]
Sorry@speedinghzl, It seems that I make a stupid mistake. Thanks for your reply!!!

**Comment by speedinghzl** [comment]
It's ok. Thanks for your question. If you have any questions, please feel free to ask.
