### ISSUE TITLE
mean iou?

### ISSUE THREAD

**Issue by ruoqianguo** [speedinghzl/Pytorch-Deeplab#16]
https://github.com/speedinghzl/Pytorch-Deeplab/blob/160c5b40f4437fda963c85e47cbc50ec5db68223/deeplab/metric.py#L54 
if self.M[i, i] == 0, then `jaccard_perclass`  will do nothing and class i will be dropped. `len(jaccard_perclass)` will be num_classes -1 ?  The results will be inaccurate. I think if self.M[i, i] == 0, the iou of class i will be 0  and shouldn't be droped.

**Comment by speedinghzl** [comment]
@guoruoqian Thanks. You are right! I have fixed it. Maybe it doesn't influence the accuracy of my repo. In general self.M[i, i] are not equal 0.

**Comment by ruoqianguo** [comment]
You are welcome!
