### ISSUE TITLE
Advising set align_corners=True for Upsample

### ISSUE THREAD

**Issue by XiaLiPKU** [speedinghzl/Pytorch-Deeplab#19]
https://github.com/speedinghzl/Pytorch-Deeplab/blob/89a49c2f340cf359cfadab29c899a74ade53ee70/evaluate.py#L120

Since pytorch 0.4.0, the default paramter for align_corners for Upsample in False, that's quite different from older version. To keep the excutation the same for different versions of pytorch, I highly advise you explicitly set it.

**Comment by speedinghzl** [comment]
@XiaLiPKU Thanks for your advice.
