### ISSUE TITLE
VOC12_scenes_20000.pth

### ISSUE THREAD

**Issue by sinemaslanx** [speedinghzl/Pytorch-Deeplab#23]
Could anybody share VOC12_scenes_20000.pth on googledrive? I couldnot install it from the link given here: https://pan.baidu.com/s/1bP52R8

in chinese and it requires me to install a exe file.. baudi..something ..

thanks in advance
sinem.

**Comment by MaureenZOU** [comment]
https://drive.google.com/open?id=19_PGrzARnJugSKULbTyRJ0txlI2UPvm6
