### ISSUE TITLE
trained resulut

### ISSUE THREAD

**Issue by mingminzhen** [speedinghzl/Pytorch-Deeplab#3]
Could you upload a .pth file for the validation 74.0%?

**Comment by speedinghzl** [comment]
You can download the trained model [VOC12_scenes_20000.pth](https://pan.baidu.com/s/1bP52R8)

**Comment by mingminzhen** [comment]
thanks!

**Comment by mingminzhen** [comment]
Another question is: could you provide the multi scale training result and .pth file?
