### ISSUE TITLE
A bug of the 'return' statement in Classifier_Module

### ISSUE THREAD

**Issue by Tangzy7** [speedinghzl/Pytorch-Deeplab#4]
https://github.com/speedinghzl/Pytorch-Deeplab/blob/master/deeplab/model.py#L116

Should it be 

    def forward(self, x):
        out = self.conv2d_list[0](x)
        for i in range(len(self.conv2d_list)-1):
            out += self.conv2d_list[i+1](x)
        return out

instead of 

    def forward(self, x):
        out = self.conv2d_list[0](x)
        for i in range(len(self.conv2d_list)-1):
            out += self.conv2d_list[i+1](x)
            return out

**Comment by speedinghzl** [comment]
Thanks for pointing this out.
