### ISSUE TITLE
There are some errors when I changed 'NUM_CLASSES'.

### ISSUE THREAD

**Issue by MarcokH** [speedinghzl/Pytorch-Deeplab#6]
i chang NUM_CLASSES=21 to NUM_CLASSES=2 ,but i meet a problem, as
**RuntimeError: inconsistent tensor size, expected tensor [2 x 2048 x 3 x 3] and src [21 x 2048 x 3 x 3] to have the same number of elements, but got 18432 and 387072 elements respectively at /pytorch/torch/lib/TH/generic/THTensorCopy.c:86_**.
it seems that pre-trained model weight doesn't match 'NUM_CLASSES=2' network,
https://github.com/speedinghzl/Pytorch-Deeplab/blob/795287e3df949a77b096508b85d49b32e9f074c1/train_msc.py#L190
how do i solve this problem?

**Comment by speedinghzl** [comment]
You need to change the Line [181](https://github.com/speedinghzl/Pytorch-Deeplab/blob/master/train.py#L181),
change
if not args.num_classes == 21 or not i_parts[1]=='layer5':
into
if args.num_classes == 21 or not i_parts[1]=='layer5':

**Comment by MarcokH** [comment]
thanks for your reply, it solved my problem,but i encounter another problem:
**RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THC/generic/THCTensorCopy.c:18**
it happened in
https://github.com/speedinghzl/Pytorch-Deeplab/blob/795287e3df949a77b096508b85d49b32e9f074c1/train_msc.py#L230
because of
https://github.com/speedinghzl/Pytorch-Deeplab/blob/795287e3df949a77b096508b85d49b32e9f074c1/train_msc.py#L107
in fact,when i tried to solve the previous question ,i met the same problem.
could you give some advice to solve the problem? thanks!

**Comment by speedinghzl** [comment]
I suggest you use the train.py script, I don't update the multi-scale version.

**Comment by Marco-HUANG** [comment]
Ok, I wil try to run the train.py script. thanks again!

**Comment by MarcokH** [comment]
Ok, I will try to run the train.py script. thanks again!
